# Dockerfile

# this is a test to see if you can push to dockerhub with a fake/unverified email: you can

# Use BusyBox as the base image
FROM busybox

# Create a file named hello.txt and write "Hello World" to it
RUN echo "Hello World" > /hello.txt
